### ISSUE TITLE
ImportError: No module named bashmagic

### ISSUE THREAD

**Issue by vanzytay** [TimDettmers/ConvE#1]
Hey!

First of all, a really great thanks for open sourcing your code. I was trying to run the code but ran into some issues with dependencies. 

```
Traceback (most recent call last):
  File "main.py", line 16, in <module>
    from spodernet.preprocessing.pipeline import Pipeline, DatasetStreamer
  File "/home/username/ConvE/src/spodernet/spodernet/preprocessing/pipeline.py", line 9, in <module>
    from spodernet.preprocessing.vocab import Vocab
  File "/home/username/ConvE/src/spodernet/spodernet/preprocessing/vocab.py", line 9, in <module>
    import bashmagic
ImportError: No module named bashmagic
```
Would appreciate if you can provide some insight to how to solve this issue. 

Many thanks!

**Comment by gsp2014** [comment]
You can just remove "import bashmagic".

**Comment by TimDettmers** [comment]
I forgot to add that dependency. It should now be working from the get-go.
