### ISSUE TITLE
Data processing returns error

### ISSUE THREAD

**Issue by leejayyoon** [TimDettmers/ConvE#24]
I did use pytorch v0.4 & python 3.6, 

there are two errors I found on data processing.

1.  running (python main.py model ConvE dataset FB15k-237 process True)
-->
Traceback (most recent call last):
  File "main.py", line 181, in <module>
    main()
  File "main.py", line 153, in main
    for i, str2var in enumerate(train_batcher):
  File "/home/jisuk1/virtual_env_dir/torch/src/spodernet/spodernet/preprocessing/batching.py", line 369, in __next__
    self.publish_end_of_iter_event()
  File "/home/jisuk1/virtual_env_dir/torch/src/spodernet/spodernet/preprocessing/batching.py", line 302, in publish_end_of_iter_event
    obs.at_end_of_iter_event(self.state)
  File "/home/jisuk1/virtual_env_dir/torch/src/spodernet/spodernet/hooks.py", line 59, in at_end_of_iter_event
    delta = metric - self.mean
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
Exception ignored in: <bound method Event.__del__ of <torch.cuda.Event 0x3b55aa0>>
Traceback (most recent call last):
  File "/share/apps/lib/python3.5/site-packages/torch/cuda/streams.py", line 164, in __del__
  File "/share/apps/lib/python3.5/site-packages/torch/cuda/__init__.py", line 188, in check_error
AttributeError: 'NoneType' object has no attribute 'SUCCESS

2. Preprocessing unicode err --> this can be fixed by individuals, but good to have it right.

Processing dataset YAGO3-10
Traceback (most recent call last):
  File "wrangle_KG.py", line 36, in <module>
    data = f.readlines() + data
  File "/home/jisuk1/anaconda3/envs/pytorch0.4/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 188: ordinal not in range(128)

**Comment by TimDettmers** [comment]
This is a bit late, but see #46 for reference.
