### ISSUE TITLE
where is evaluation{0}.py.txt 

### ISSUE THREAD

**Issue by Lazy-poe** [TimDettmers/ConvE#56]
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    from evaluation import ranking_and_hits
  File "D:\github\ConvE\evaluation.py", line 9, in <module>
    log = Logger('evaluation{0}.py.txt'.format(datetime.datetime.now()))
  File "d:\github\conve\src\spodernet\spodernet\utils\logger.py", line 64, in __init__
    self.f = open(path, write_type)
OSError: [Errno 22] Invalid argument: 'C:\\Users\\11840\\.data\\log_files\\evaluation2019-12-25 23:46:51.964885.py.txt'
Exception ignored in: <function Logger.__del__ at 0x000002A0E5EE6CA8>
Traceback (most recent call last):
  File "d:\github\conve\src\spodernet\spodernet\utils\logger.py", line 71, in __del__
    self.f.close()
AttributeError: 'Logger' object has no attribute 'f'
(py_37)

**Comment by TimDettmers** [comment]
I never tested my library with Windows and there seem to be some issues with that. Unfortunately, I do not have the time to look into this in detail. Would you have some time to debug it a little bit? Maybe I could help you to fix it and everyone would benefit from that.

**Comment by Lazy-poe** [comment]
I will test these library later,  thank for your supports.

**Comment by Bryan2Chow** [comment]
I would like to know about it as well.
I am very pleased to hear from you on the question's comments. @TimDettmers @Lazy-poe

**Comment by StarAx0519** [comment]
> I would like to know about it as well. I am very pleased to hear from you on the question's comments. @TimDettmers @Lazy-poe

I would like to know about the question on windows as well and I met the same errot as you. I sincerely need the help.
