### ISSUE TITLE
changing embedding-dim

### ISSUE THREAD

**Issue by saeedizade** [TimDettmers/ConvE#70]
hi, thank you for sharing this code.
i cant change embedding-dim parameter , when i change, i get this error : 
```
Traceback (most recent call last):
  File "main.py", line 202, in <module>
    main(args, model_path)
  File "main.py", line 143, in main
    pred = model.forward(e1, rel)
  File "/content/ConvE/model.py", line 116, in forward
    x = self.fc(x)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/linear.py", line 91, in forward
    return F.linear(input, self.weight, self.bias)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 1674, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: mat1 dim 1 must match mat2 dim 0

```

**Comment by TimDettmers** [comment]
Please see the (Changing the embedding size for ConvE)[Changing the embedding size for ConvE] for more information about how to change the embedding dimension. In your case, the error message does not say the explicit dimension. I wonder if this is related to your PyTorch version. Which PyTorch version are you using?
